#!/bin/sh

#sv start socklog-unix || exit 1

FIFO=/dev/shm/command-fifo
rm -f ${FIFO}
mkfifo ${FIFO}

# eula
cp /eula.txt /data

#copy plugins
rsync -av /plugins/ /data/plugins/ --delete

cd /data
exec 2>&1
exec java -server -Xmx2G -Xms512M -XX:+UseConcMarkSweepGC -jar /spigot*.jar nogui <> ${FIFO}
